---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '30 1 * * 3'
jobs:
  lint:
    name: Lint
    runs-on: rockylinux9
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install test dependencies
        run: |
          pip install ansible-lint

      - name: Lint code
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: rockylinux9
    defaults:
      run:
        working-directory: "${{ github.repository }}"
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: rockylinux9

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install test dependencies
        run: pip install ansible molecule-plugins[docker] docker

      - name: Run Molecule tests
        run: |
          molecule test
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_VERBOSITY: '2'
          MOLECULE_DEBUG: '1'
          MOLECULE_DISTRO: "${{ matrix.distro }}"
          PY_COLORS: '1'
